### ISSUE TITLE
The blue eagle has perched on the palm tree

### ISSUE THREAD

**Issue by aashah** [APShirley/secret-service#1]

**Comment by APShirley** [comment]
Roger. Contacting KILO LIMA FOXTROT CHARLIE CHARLIE. Please remain in a holding pattern at 330 over.

**Comment by bottomqueer** [comment]
Hey.. Im a girly guy.. Bottom bitch u can fuck looking today.. I wear girl clothes paint my nails hit me up 865 888 1285
Knoxvilletn37918@gmail.com
